# Generated by Django 2.2 on 2019-04-17 12:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('requets', '0008_auto_20190417_1408'),
        ('users', '0003_auto_20190417_1407'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='company',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='requets.Company'),
        ),
        migrations.AddField(
            model_name='profile',
            name='personne',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='requets.Personne'),
        ),
    ]
