# Generated by Django 2.2 on 2019-04-16 09:04

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('requets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='requet',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 16, 9, 4, 43, 473807, tzinfo=utc)),
        ),
    ]
