# Generated by Django 2.2 on 2019-04-17 11:51

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('requets', '0003_auto_20190417_1046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requet',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 17, 11, 51, 31, 167884, tzinfo=utc)),
        ),
    ]
