# Generated by Django 2.2 on 2019-04-17 11:54

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('requets', '0004_auto_20190417_1351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requet',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 17, 11, 54, 0, 391419, tzinfo=utc)),
        ),
    ]
