# Generated by Django 2.2 on 2019-04-17 12:08

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('requets', '0007_auto_20190417_1407'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requet',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 17, 12, 8, 5, 427753, tzinfo=utc)),
        ),
    ]
