# Generated by Django 2.2 on 2019-04-17 12:59

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20190417_1459'),
        ('requets', '0008_auto_20190417_1408'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Company',
        ),
        migrations.DeleteModel(
            name='Personne',
        ),
        migrations.AlterField(
            model_name='requet',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 17, 12, 59, 26, 528982, tzinfo=utc)),
        ),
    ]
