# Generated by Django 2.2 on 2019-04-22 11:54

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('requets', '0009_auto_20190417_1459'),
    ]

    operations = [
        migrations.AddField(
            model_name='requet',
            name='fix_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='requet',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 22, 11, 54, 46, 514708, tzinfo=utc)),
        ),
    ]
