# Generated by Django 2.2 on 2019-04-23 11:28

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('requets', '0010_auto_20190422_1354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requet',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 23, 11, 28, 22, 477130, tzinfo=utc)),
        ),
    ]
