# Generated by Django 2.2 on 2019-04-23 13:37

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('requets', '0011_auto_20190423_1328'),
    ]

    operations = [
        migrations.AddField(
            model_name='requet',
            name='problem',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='requet',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 23, 13, 37, 24, 318938, tzinfo=utc)),
        ),
    ]
