# Generated by Django 2.2 on 2019-04-24 10:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('requets', '0012_auto_20190423_1537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requet',
            name='pub_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
