# Generated by Django 2.2 on 2019-04-26 09:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('requets', '0013_auto_20190424_1224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requet',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requets', related_query_name='requet', to=settings.AUTH_USER_MODEL),
        ),
    ]
