# Generated by Django 2.2 on 2019-04-26 09:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('requets', '0014_auto_20190426_1110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requet',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requets', to=settings.AUTH_USER_MODEL),
        ),
    ]
