# Generated by Django 2.2 on 2019-04-26 10:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('requets', '0015_auto_20190426_1134'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nots', to=settings.AUTH_USER_MODEL)),
                ('requet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nots', to='requets.Requet')),
            ],
        ),
    ]
