# Generated by Django 2.2 on 2019-04-26 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requets', '0016_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='requet',
            name='fix_confirm',
            field=models.BooleanField(default=False),
        ),
    ]
